import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { NavigationBar } from '@/components/navbar/navigationBar'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider signInUrl="/auth/sign-in" signUpUrl="/auth/sign-up">
      <html lang="en">
        <body className={`${roboto.variable} antialiased`}>
          <NavigationBar />

          <main className="flex flex-col items-center">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}
