/* eslint-disable @next/next/no-img-element */
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <nav className="bg-primary h-12 flexCol">
          <img className="h-10" src="/jayob_logo_white.svg" alt="Jayob Logo" />
        </nav>
        {children}
      </body>
    </html>
  )
}
